Add Actions & Reducers
umair-rao/Bookstore pull request #2
Opened 2022-12-22 14:39 UTC by umair-rao

In this pull request, I have added actions and reducers for books and categories as per instructions. 
After that, the reducers are combined with the configure store function and added to the redux store.

You are requested to please review my PR.

Thank you.

2022-12-22 15:33 UTC, GzimAsani requested changes
### Hello  @umair-rao                                  :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your project structure and configuring your store :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 



 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 15:33 UTC, GzimAsani commented on src/redux/books/books.js
> +});
- [ ] Please define ADD_BOOK and REMOVE_BOOK as action types (names can be slightly different). The value of each action type needs to follow the [ducks pattern](https://github.com/erikras/ducks-modular-redux), so it will be something like:       const ADD_BOOK = bookstore/books/ADD_BOOK and const REMOVE_BOOK = bookstore/books/REMOVE_BOOK
- [ ] Set an initial state with an empty array.
- **Good job creating and Exports **Action Creators**. (`addBook` and `removeBook` functions)**
- [ ] Please create a reducer and export it as default, in the case`action.type` is `ADD_BOOK` it returns a new state object in which the books array will contain a new book object, passed by action.payload. In case `action.type` is `REMOVE_BOOK` the function use ES6 filter() method to create a new array, which will not contain the book you want to remove from the store
- [ ] if the `action.type` is different, it returns the state with no changes.
- [ ] Same requirements for creating action types goes for the categories as well

2022-12-23 08:11 UTC, umair-rao commented on src/redux/books/books.js
> +});
All the suggested changes have been made. Thank you for taking the time to have a depth explanation which helped me a lot while understanding the requirements.

2022-12-23 08:35 UTC, Abenezer-Tilahun commented on src/redux/books/books.js
> +});
Fixed.

2022-12-23 08:50 UTC, Abenezer-Tilahun approved these changes
Hi @umair-rao 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Bookstore: add reducers and actions

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 09:52 UTC, merged